databases:
  - name: sonar_v2
    databaseName: sonar_production
    user: sonar_v2

services:
  - type: web
    name: sonar_v2
    runtime: ruby
    buildCommand: "./bin/sonar-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sonar_v2
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
